[[language]]
name = "astro"
scope = "source.astro"
injection-regex = "astro"
file-types = ["astro"]
language-servers = ["astro-ls", "tailwind-ls"]
# formatter = { command = "prettier", args = ["--config", "./.prettierrc.mjs", "--parser", "astro"] }
auto-format = true

[[language]]
name = "tsx"
scope = "source.tsx"
injection-regex = "^(tsx)$"
file-types = ["tsx"]
language-servers = ["astro-ls", "tailwind-ls"]
# formatter = { command = "prettier", args = ["--config", "./.prettierrc.mjs", "--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
language-id = "typescript"
scope = "source.ts"
injection-regex = "^(ts|typescript)$"
language-servers = ["astro-ls", "tailwind-ls"]
# formatter = { command = "prettier", args = ["--config", "./.prettierrc.mjs", "--parser", "typescript"] }
auto-format = true

[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]
config = { typescript = { tsdk = "/Users/brett/Workspace/blazers/node_modules/typescript/lib" }}

[language-server.tailwind-ls]
args = ["--stdio"]
command = "tailwindcss-language-server"

